<?php

namespace SSql\Sql;

require_once dirname(dirname(__FILE__)) . "/src/SSql.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-05 at 10:09:50.
 */
class InvalidParameterCommentTest extends \PHPUnit_Framework_TestCase {

    /**
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
  	}

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
	/**
	 * @expectedException \SSql\Exception\EndCommentNotFoundException
	 */
    public function test1() {
		$sql = "/*BEGIN*/";
		$sql .= "/*IF true*/a = 1/*END*/";
		$an = new SqlAnalyzer($sql);
		$node = $an->analyze();
   }

	/**
	 */
    public function test1Ok() {
		$sql = "/*BEGIN*/";
		$sql .= "/*IF true*/a = 1/*END*/";
		$sql .= "/*END*/";
		$an = new SqlAnalyzer($sql);
		$node = $an->analyze();
		// ok
		$this->assertTrue(true);
   }

	/**
	 * @expectedException \SSql\Exception\EndCommentNotFoundException
	 */
    public function test2() {
		$sql = "/*BEGIN*/";
		$sql .= "/*IF true*/a = 1";
		$sql .= "/*END*/";
		$an = new SqlAnalyzer($sql);
		$node = $an->analyze();
   }

	/**
	 * @expectedException \SSql\Exception\IfCommentConditionEmptyException
	 */
    public function test3() {
		$sql = "/*IF*/a = 1/*END*/";
		$an = new SqlAnalyzer($sql);
		$node = $an->analyze();
   }

	/**
	 */
    public function test3Ok() {
		$sql = "/*IF true*/a = 1/*END*/";
		$an = new SqlAnalyzer($sql);
		$node = $an->analyze();
		$this->assertTrue(true);
   }

   /**
    */
   public function test4() {
		$sql = "/*IF a != null*/a = /*b*/1/*END*/";
		$an = new SqlAnalyzer($sql);
		$node = $an->analyze();
		$param = array('a' => 4999);
		$context = Context\CommandContext::createCommandContext($param);
		$node->acceptContext($context);
   }

   /**
    */
   public function test5() {
		$sql = "/*IF a != null*/a = /*b*/1/*END*/";
		$an = new SqlAnalyzer($sql);
		$node = $an->analyze();
		$param = array();
		$context = Context\CommandContext::createCommandContext($param);
		$node->acceptContext($context);
		$this->assertTrue(true);
   }

   /**
    */
   public function test6() {
		$sql = "/*IF a != null*/a = /*b*/1/*END*/";
		$an = new SqlAnalyzer($sql);
		$node = $an->analyze();
		$param = array('a' => 4999, 'b' => null);
		$context = Context\CommandContext::createCommandContext($param);
		$node->acceptContext($context);
   }


}

