languge: php

php:
  - 5.3

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - psql -c "create database user;"
  - mysql -e "create database user;"

script: phpunit --coverage-text

notification:
  email: amkt922@gmail.com
