languge: php

php:
  - 5.3

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database user;"; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database user;"; fi

script: phpunit --coverage-text

notification:
  email: amkt922@gmail.com
