language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql
  - DB=sqlite
  - DB=pgsql

before_script:
  - composer install
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS ssql_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database ssql_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS ssql_test;" -uroot; fi

script: 
  - phpunit -c test/ci_phpunit_$DB.xml

notification:
  email: amkt922@gmail.com
